// Code generated by sqlc. DO NOT EDIT.

package authdb

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddApplicationRole(ctx context.Context, arg AddApplicationRoleParams) (ApplicationsRole, error)
	AddUserLanguage(ctx context.Context, arg AddUserLanguageParams) (UserLanguage, error)
	AddUserProvider(ctx context.Context, arg AddUserProviderParams) (UserProvider, error)
	AddUserRole(ctx context.Context, arg AddUserRoleParams) (UserRole, error)
	AddUserTimezone(ctx context.Context, arg AddUserTimezoneParams) (UserTimezone, error)
	CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error)
	CreateIdentityProvider(ctx context.Context, arg CreateIdentityProviderParams) (IdentityProvider, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateTimezone(ctx context.Context, arg CreateTimezoneParams) (Timezone, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserLogin(ctx context.Context, arg CreateUserLoginParams) (UserLogin, error)
	DeleteApplication(ctx context.Context, name string) error
	DeleteCountry(ctx context.Context, name string) error
	DeleteIdentityProvider(ctx context.Context, name string) error
	DeleteLanguage(ctx context.Context, name string) error
	DeleteRefreshToken(ctx context.Context, token string) error
	DeleteRoles(ctx context.Context, name string) error
	DeleteTimezone(ctx context.Context, name string) error
	DeleteUser(ctx context.Context) error
	DeleteUserLogin(ctx context.Context, arg DeleteUserLoginParams) error
	GetApplication(ctx context.Context, name string) (Application, error)
	GetApplicationRole(ctx context.Context, arg GetApplicationRoleParams) (ApplicationsRole, error)
	GetApplications(ctx context.Context) ([]Application, error)
	GetCountries(ctx context.Context) ([]Country, error)
	GetCountry(ctx context.Context, name string) (Country, error)
	GetIdentityProvider(ctx context.Context, name string) (IdentityProvider, error)
	GetIdentityProviders(ctx context.Context) ([]IdentityProvider, error)
	GetLanguage(ctx context.Context, name string) (Language, error)
	GetLanguages(ctx context.Context) ([]Language, error)
	GetRefreshToken(ctx context.Context, token string) (RefreshToken, error)
	GetRefreshTokens(ctx context.Context) ([]RefreshToken, error)
	GetRole(ctx context.Context, name string) (Role, error)
	GetRoles(ctx context.Context) ([]Role, error)
	GetTimezone(ctx context.Context, name string) (Timezone, error)
	GetTimezones(ctx context.Context) ([]Timezone, error)
	GetUnResoledLogins(ctx context.Context, userID sql.NullInt64) ([]UserLogin, error)
	GetUser(ctx context.Context, username sql.NullString) (UserDetail, error)
	GetUserLogin(ctx context.Context, userID sql.NullInt64) ([]UserLogin, error)
	GetUserLogins(ctx context.Context) ([]UserLogin, error)
	GetUserRoles(ctx context.Context, userID sql.NullInt64) ([]string, error)
	GetUsers(ctx context.Context) ([]UserDetail, error)
	UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (Application, error)
	UpdateApplicationRole(ctx context.Context, arg UpdateApplicationRoleParams) (ApplicationsRole, error)
	UpdateCountry(ctx context.Context, arg UpdateCountryParams) (Country, error)
	UpdateIdentityProvider(ctx context.Context, arg UpdateIdentityProviderParams) (IdentityProvider, error)
	UpdateLanguage(ctx context.Context, arg UpdateLanguageParams) (Language, error)
	UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) (RefreshToken, error)
	UpdateResolvedLogin(ctx context.Context, userID sql.NullInt64) error
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateTimezone(ctx context.Context, arg UpdateTimezoneParams) (Timezone, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserLanguage(ctx context.Context, arg UpdateUserLanguageParams) (UserLanguage, error)
	UpdateUserProvider(ctx context.Context, arg UpdateUserProviderParams) (UserProvider, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (UserRole, error)
	UpdateUserTimezone(ctx context.Context, arg UpdateUserTimezoneParams) (UserTimezone, error)
}

var _ Querier = (*Queries)(nil)
