// Code generated by sqlc. DO NOT EDIT.
// source: contactBlock.sql

package helloprofiledb

import (
	"context"

	"github.com/google/uuid"
)

const addContactBlock = `-- name: AddContactBlock :one
insert into contact_block(
    phone,
    email,
    "address",
    website 
)VALUES(
    $1, $2, $3, $4
) RETURNING id, phone, email, address, website
`

type AddContactBlockParams struct {
	Phone   string `json:"phone"`
	Email   string `json:"email"`
	Address string `json:"address"`
	Website string `json:"website"`
}

func (q *Queries) AddContactBlock(ctx context.Context, arg AddContactBlockParams) (ContactBlock, error) {
	row := q.queryRow(ctx, q.addContactBlockStmt, addContactBlock,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.Website,
	)
	var i ContactBlock
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.Website,
	)
	return i, err
}

const deleteContactBlock = `-- name: DeleteContactBlock :exec
delete from contact_block where id=$1
`

func (q *Queries) DeleteContactBlock(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.deleteContactBlockStmt, deleteContactBlock, id)
	return err
}

const getContactBlock = `-- name: GetContactBlock :one
select id, phone, email, address, website from contact_block where id=$1 limit 1
`

func (q *Queries) GetContactBlock(ctx context.Context, id uuid.UUID) (ContactBlock, error) {
	row := q.queryRow(ctx, q.getContactBlockStmt, getContactBlock, id)
	var i ContactBlock
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.Website,
	)
	return i, err
}

const updateContactBlock = `-- name: UpdateContactBlock :exec
update contact_block set phone=$1,
    email=$2,
    "address"=$3,
    website=$4 where id=$5
`

type UpdateContactBlockParams struct {
	Phone   string    `json:"phone"`
	Email   string    `json:"email"`
	Address string    `json:"address"`
	Website string    `json:"website"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) UpdateContactBlock(ctx context.Context, arg UpdateContactBlockParams) error {
	_, err := q.exec(ctx, q.updateContactBlockStmt, updateContactBlock,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.Website,
		arg.ID,
	)
	return err
}
