apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helloprofile-logs
  namespace: default
  labels:
    app: helloprofile
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeName: pv-helloprofile-logs
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-helloprofile-logs
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/usr/local/bin/log"