apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloprofile-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-test
spec:
  tls:
  - hosts:
    - test.api.helloprofile.io
    - helloprofile.test.api.devtroy.com
    secretName: hello-kubernetes-tls
  rules:
  - host: "test.api.helloprofile.io"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: helloprofile-service
            port:
              number: 8083
  - host: "helloprofile.test.api.devtroy.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: helloprofile-service
            port:
              number: 8083