apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-cert
spec:
  domains:
    - helloprofile.test.api.devtroy.com
    - communication.test.api.devtroy.com
    - test.api.helloprofile.io
